=== dragmine149/Work/Gigantic/Schema/TTschema.json
{
    "$schema": "http://json-schema.org/schema",
    "title": "Timetable",
    "description": "A timetable consisting of 5 lessons per day.",
    "type": "object",
    "properties": {
        "Monday": {
            "description": "Lessons on monday",
            "type": "object",
            "$ref": "DaySchema.json"
        },
        "Tuesday": {
            "description": "Lessons on Tuesday",
            "type": "object",
            "$ref": "DaySchema.json"
        },
        "Wednesday": {
            "description": "Lessons on Wednesday",
            "type": "object",
            "$ref": "DaySchema.json"
        },
        "Thursday": {
            "description": "Lessons on Thursday",
            "type": "object",
            "$ref": "DaySchema.json"
        },
        "Friday": {
            "description": "Lessons on Friday",
            "type": "object",
            "$ref": "DaySchema.json"
        }
    },
    "required": [ "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
}

=== dragmine149/Work/Gigantic/Data/TimeTable.json
{
    "$schema": "../Schema/TTschema.json",
    "Monday": {
        "Lesson 1": {
            "Lesson": "",
            "Room": "",
            "Teacher": ""
        },
        "Lesson 2": {
            "Lesson": "",
            "Room": "",
            "Teacher": ""
        },
        "Lesson 3": {
            "Lesson": "Computer Science",
            "Room": "G49",
            "Teacher": "PTE"
        },
        "Lesson 4": {
            "Lesson":"Computer Science",
            "Room": "G49",
            "Teacher": "PTE"
        },
        "Lesson 5": {
            "Lesson": "IT",
            "Room": "G49",
            "Teacher": "IKN"
        }
    },
    "Tuesday": {
        "Lesson 1": {
            "Lesson": "Study",
            "Room": "BLIB",
            "Teacher": "KGA"
        },
        "Lesson 2": {
            "Lesson": "",
            "Room": "",
            "Teacher": ""
        },
        "Lesson 3": {
            "Lesson": "Maths",
            "Room": "G02",
            "Teacher": "ZPA"
        },
        "Lesson 4": {
            "Lesson": "Maths",
            "Room": "G04",
            "Teacher": "DKA"
        },
        "Lesson 5": {
            "Lesson": "",
            "Room": "",
            "Teacher": ""
        }
    },
    "Wednesday": {
        "Lesson 1": {
            "Lesson": "Computer Science",
            "Room": "G49",
            "Teacher": "AJA"
        },
        "Lesson 2": {
            "Lesson": "",
            "Room": "",
            "Teacher": ""
        },
        "Lesson 3": {
            "Lesson": "IT",
            "Room": "G49",
            "Teacher": "AJA"
        },
        "Lesson 4": {
            "Lesson": "IT",
            "Room": "G49",
            "Teacher": "AJA"
        },
        "Lesson 5": {
            "Lesson": "",
            "Room": "",
            "Teacher": ""
        }
    },
    "Thursday": {
        "Lesson 1": {
            "Lesson": "Maths",
            "Room": "G02",
            "Teacher": "ZPA"
        },
        "Lesson 2": {
            "Lesson": "Maths",
            "Room": "G04",
            "Teacher": "DKA"
        },
        "Lesson 3": {
            "Lesson": "",
            "Room": "",
            "Teacher": ""
        },
        "Lesson 4": {
            "Lesson": "",
            "Room": "",
            "Teacher": ""
        },
        "Lesson 5": {
            "Lesson": "Computer Science",
            "Room": "G49",
            "Teacher": "AJA"
        }
    },
    "Friday": {
        "Lesson 1": {
            "Lesson": "IT",
            "Room": "G49",
            "Teacher": "IKN"
        },
        "Lesson 2": {
            "Lesson": "IT",
            "Room": "G49",
            "Teacher": "IKN"
        },
        "Lesson 3": {
            "Lesson": "",
            "Room": "",
            "Teacher": ""
        },
        "Lesson 4": {
            "Lesson": "",
            "Room": "",
            "Teacher": ""
        },
        "Lesson 5": {
            "Lesson": "",
            "Room": "",
            "Teacher": ""
        }
    }
}
